// src/constants/locations.ts
export const LOCATIONS = [
    'Amsterdam, Netherlands',
    'Bandung, Indonesia',
    'Bangkok, Thailand',
    'Barcelona, Spain',
    'Beijing, China',
    'Berlin, Germany',
    'Bogor, Indonesia',
    'Boston, United States',
    'Buenos Aires, Argentina',
    'Cairo, Egypt',
    'California, United States',
    'Califon, United States',
    'California City, United States',
    'Chicago, United States',
    'Delhi, India',
    'Denpasar, Indonesia',
    'Dubai, UAE',
    'Dublin, Ireland',
    'Hong Kong, China',
    'Houston, United States',
    'Istanbul, Turkey',
    'Jakarta, Indonesia',
    'Kuala Lumpur, Malaysia',
    'London, United Kingdom',
    'Los Angeles, United States',
    'Madrid, Spain',
    'Makassar, Indonesia',
    'Manila, Philippines',
    'Medan, Indonesia',
    'Mexico City, Mexico',
    'Moscow, Russia',
    'Mumbai, India',
    'New York, United States',
    'Paris, France',
    'Rome, Italy',
    'San Francisco, United States',
    'Sao Paulo, Brazil',
    'Seoul, South Korea',
    'Shanghai, China',
    'Singapore, Singapore',
    'Surabaya, Indonesia',
    'Sydney, Australia',
    'Tokyo, Japan',
    'Toronto, Canada',
    'Yogyakarta, Indonesia',
  ];