export const jobs = [
    {
        id: '1',
        logo: 'google',
        title: 'UI/UX Designer',
        company: 'Google inc',
        location: 'California, USA',
        tags: ['Design', 'Full time', 'Senior designer'],
        posted: '25 minute ago',
        salary: '$15K/Mo',
        logoBackgroundColor: '#FFFFFF',
        logoColor: '#4285F4',
    },
    {
        id: '2',
        logo: 'dribbble',
        title: 'Lead Designer',
        company: 'Dribbble inc',
        location: 'California, USA',
        tags: ['Design', 'Full time', 'Senior designer'],
        posted: '25 minute ago',
        salary: '$20K/Mo',
        logoBackgroundColor: '#FCEEF5',
        logoColor: '#EA4C89',
    },
    {
        id: '3',
        logo: 'twitter',
        title: 'UX Researcher',
        company: 'Twitter inc',
        location: 'California, USA',
        tags: ['Design', 'Full time', 'Senior designer'],
        posted: '25 minute ago',
        salary: '$12K/Mo',
        logoBackgroundColor: '#E7F5FE',
        logoColor: '#1DA1F2',
    },
];